project:
  type: website
  output-dir: ../docs/
website:
  title: SimpleDesign
  code-links: true
  navbar:
    search: true
    right:
      - icon: github
        href: https://github.com/vincentarelbundock/marginaleffects
        aria-label: SimpleDesign GitHub
  sidebar:
    collapse-level: 1
    contents:
      - text: Home
        file: index.md
      - section: Reference
        contents:
          - text: diagnose
            file: man/diagnose.qmd
          - text: extract_estimates
            file: man/extract_estimates.qmd
      - text: Citation
        file: CITATION.md
format:
  html:
    code-link: true
